artifact_uri: file:///Users/Tolu/MachineLearning/madewithml/credit_card_fraud_detection/mlflow_experiment_logs/463372152353211732/7cbda62561ac4c0881738d14d5db54e5/artifacts
end_time: 1723796710713
entry_point_name: ''
experiment_id: '463372152353211732'
lifecycle_stage: active
run_id: 7cbda62561ac4c0881738d14d5db54e5
run_name: IForest_Model_Run_test
run_uuid: 7cbda62561ac4c0881738d14d5db54e5
source_name: ''
source_type: 4
source_version: ''
start_time: 1723796709389
status: 3
tags: []
user_id: Tolu
