artifact_location: file:///Users/Tolu/MachineLearning/madewithml/credit_card_fraud_detection/mlflow_experiment_logs/463372152353211732
creation_time: 1723796703867
experiment_id: '463372152353211732'
last_update_time: 1723796703867
lifecycle_stage: active
name: Credit_Card_Fraud_Detection_Experiment
