artifact_uri: file:///Users/Tolu/MachineLearning/madewithml/credit_card_fraud_detection/mlflow_experiment_logs/463372152353211732/fe2665d82dba41f0b27e71eea1943c19/artifacts
end_time: 1723796706407
entry_point_name: ''
experiment_id: '463372152353211732'
lifecycle_stage: active
run_id: fe2665d82dba41f0b27e71eea1943c19
run_name: KNN_Model_Run_test
run_uuid: fe2665d82dba41f0b27e71eea1943c19
source_name: ''
source_type: 4
source_version: ''
start_time: 1723796704061
status: 3
tags: []
user_id: Tolu
